version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    container_name: app
    volumes:
      - ./src/:/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8540:8000"


  db:
    image: mariadb
    container_name: mariadb
    # volumes:
    #   - ./db_data:/var/lib/mysql
    env_file:
      - .env
    